Training main page
CatDevelop/Teaching-RSL pull request #7
Opened 2023-09-23 10:32 UTC by IrkaTyman

2023-09-23 17:46 UTC, CatDevelop requested changes
Заменить Tooltip с react-tooltip на NextUI

2023-09-23 17:46 UTC, CatDevelop commented on src/features/training/pages/TrainingCatalogPage/TrainingCatalogPage.tsx
> +                    <Tooltip anchorSelect={`.${styles.trainingCatalog__randomTest}`}>
У NextUI есть свои tooltip https://nextui.org/docs/components/tooltip

2023-09-24 11:46 UTC, IrkaTyman commented on src/features/training/pages/TrainingCatalogPage/TrainingCatalogPage.tsx
> +                    <Tooltip anchorSelect={`.${styles.trainingCatalog__randomTest}`}>
Они криво работают

2023-09-24 12:43 UTC, CatDevelop approved these changes

2023-09-24 12:44 UTC, merged